### ISSUE TITLE
1.16.2 paper server cant load TARDISChunkGenerator

### ISSUE THREAD

**Issue by Feikovandijk** [eccentricdevotion/TARDISChunkGenerator#2]
Hia,
I'm probably missing something here but after updating my server to 1.16.2 with TARDIS version 2188, ChunkGenerator version 107 and Paper version 144 I keep getting errors that paper can not load the chunk generator plugin. Here is the log:

[17:01:28 ERROR]: Could not load 'plugins/TARDISChunkGenerator.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R2/IChatBaseComponent
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.1.jar:git-Paper-137]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.1.jar:git-Paper-137]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.1.jar:git-Paper-137]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-137]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-137]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-137]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-137]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R2/IChatBaseComponent
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_262]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.1.jar:git-Paper-137]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.1.jar:git-Paper-137]
... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R2.IChatBaseComponent
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.16.1.jar:git-Paper-137]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-137]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_262]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.16.1.jar:git-Paper-137]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.1.jar:git-Paper-137]
... 7 more

Is there anything I'm missing here?

**Comment by eccentricdevotion** [comment]
> [patched_1.16.1.jar:git-Paper-137]

You're still running a 1.16.1 server...
You actually need [Paper 144](https://papermc.io/api/v1/paper/1.16.2/144/download) - the download link on the Paper page is broken

**Comment by Feikovandijk** [comment]
That's awkward, all the warnings are hard to miss. Paper 144 works like a charm, thank you ;)
